
services:
  - type: web
    name: neon-chat
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neonchat-db
          property: connectionString

      - key: ENCRYPTION_KEY
        sync: false

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: TELEGRAM_CHAT_ID
        sync: false

    regions:
      - singapore   # best for India users

databases:
  - name: neonchat-db
    plan: free
